baseURL = ""
languageCode = "en-us"
theme = "SimpleIntro"
title = "Relojeria Esquina Favorita"
publishDir = "public"

[params]
    mainbg = "background2.jpg"
    name = "Relojeria Esquina Favorita"
    mainTitle = "En el corazon de la Galeria Favorita"
    mainText = "Desde 1999"

[menus]
    [[menu.main]]
        identifier = "contactanos"
        name = "Contactanos"
        url = "#contactanos"
    [[menu.main]]
        identifier = "reparaciones"
        name = "Reparaciones"
        url = "#reparaciones"
    [[menu.main]]
        identifier = "marcas"
        name = "Marcas"
        url = "#marcas"